export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

//ASYNC CONSTS
export const REQUEST_VENUES_PENDING = 'REQUEST_VENUES_PENDING';
export const REQUEST_VENUES_SUCCESS = 'REQUEST_VENUES_SUCCESS';
export const REQUEST_VENUES_FAILED = 'REQUEST_VENUES_FAILED';